baseURL = "https://itssamuelrowe.github.io/binarystars/"
languageCode = "en-us"
title = "Binary Stars"
theme = "grav"

[params]
    themeVariant = "green"
    showVisitedLinks = true
    author = "Samuel Rowe"